package osakerekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import osakerekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.05 13:16:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OsakeTest {



  // Generated by ComTest BEGIN
  /** testGetName48 */
  @Test
  public void testGetName48() {    // Osake: 48
    Osake stock = new Osake(); 
    stock.giveStock(0); 
    { String _l_=stock.getName(),_r_=""; if ( !_l_.matches(_r_) ) fail("From: Osake line: 51" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRegister98 */
  @Test
  public void testRegister98() {    // Osake: 98
    Osake osake1 = new Osake(); 
    assertEquals("From: Osake line: 100", 0, osake1.getId()); 
    assertEquals("From: Osake line: 101", 2, osake1.register()); 
    Osake osake2 = new Osake(); 
    osake2.register(); 
    int n1 = osake1.getId(); 
    int n2 = osake2.getId(); 
    assertEquals("From: Osake line: 106", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone184 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone184() throws CloneNotSupportedException {    // Osake: 184
    Osake stock = new Osake(); 
    stock.parse("1|Nokia Oyj|200|3.12|624.00|"); 
    Osake kopio = stock.clone(); 
    assertEquals("From: Osake line: 189", stock.toString(), kopio.toString()); 
    stock.parse("2|Olvi Oyj|20|20.00|400.00|"); 
    assertEquals("From: Osake line: 191", false, kopio.toString().equals(stock.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString217 */
  @Test
  public void testToString217() {    // Osake: 217
    Osake stock = new Osake(); 
    stock.parse("1|Nokia Oyj|200|3.12|624.00|"); 
    assertEquals("From: Osake line: 220", false, stock.toString().startsWith("1|Nokia Oyj|200|3.12|624.00|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse240 */
  @Test
  public void testParse240() {    // Osake: 240
    Osake stock = new Osake(); 
    stock.parse("1|Nokia Oyj|200|3.12|624.00|"); 
    assertEquals("From: Osake line: 243", 1, stock.getId()); 
    assertEquals("From: Osake line: 244", true, stock.toString().startsWith("1|Nokia Oyj|200|3.12|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    stock.register(); 
    int n = stock.getId(); 
    stock.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    stock.register();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Osake line: 250", n+20+1, stock.getId()); 
  } // Generated by ComTest END
}