package osakerekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import osakerekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.05 22:08:05 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class StoreExceptionTest {
}