package osakerekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import osakerekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.04.29 13:29:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TransaktioTest {



  // Generated by ComTest BEGIN
  /** testRegister110 */
  @Test
  public void testRegister110() {    // Transaktio: 110
    Transaktio trans1 = new Transaktio(); 
    assertEquals("From: Transaktio line: 112", 0, trans1.getTransactionId()); 
    trans1.register(); 
    Transaktio trans2 = new Transaktio(); 
    trans2.register(); 
    int n1 = trans1.getTransactionId(); 
    int n2 = trans2.getTransactionId(); 
    assertEquals("From: Transaktio line: 118", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString206 */
  @Test
  public void testToString206() {    // Transaktio: 206
    Transaktio transaktio = new Transaktio(); 
    transaktio.parse("1 | 1 | 2007-11-30 | Osto | 27.32 | 200 | 54.64 | 5518.64 |"); 
    assertEquals("From: Transaktio line: 209", "1|1|2007-11-30|Osto|27.32|200|54.64|5518.64|", transaktio.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse231 */
  @Test
  public void testParse231() {    // Transaktio: 231
    Transaktio transaction = new Transaktio(); 
    transaction.parse("1 | 1 | 30.11.2007 | Osto | 27.32 | 200 | 54.64 | 5518.64 |"); 
    assertEquals("From: Transaktio line: 234", 3, transaction.getTransactionId()); 
    assertEquals("From: Transaktio line: 235", true, transaction.toString().startsWith("1 | 1 | 30.11.2007 | Osto | 27.32 | 200 | 54.64 | 5518.64 |"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    transaction.register(); 
    int n = transaction.getTransactionId(); 
    transaction.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    transaction.register();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Transaktio line: 241", n+20+1, transaction.getTransactionId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone267 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone267() throws CloneNotSupportedException {    // Transaktio: 267
    Transaktio trans = new Transaktio(); 
    trans.parse("   2   |  10  |   Kalastus  | 1949 | 22 t "); 
    Transaktio klooni = trans.clone(); 
    assertEquals("From: Transaktio line: 272", trans.toString(), klooni.toString()); 
    trans.parse("   1   |  11  |   Uinti  | 1949 | 22 t "); 
    assertEquals("From: Transaktio line: 274", false, klooni.toString().equals(trans.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGiveTransaction350 */
  @Test
  public void testGiveTransaction350() {    // Transaktio: 350
    Transaktio trans = new Transaktio(); 
    trans.parse("   2   |  10  |   Kalastus  | 1949 | 22 t "); 
    assertEquals("From: Transaktio line: 353", "2", trans.giveTransaction(0)); 
    assertEquals("From: Transaktio line: 354", "10", trans.giveTransaction(1)); 
    assertEquals("From: Transaktio line: 355", "Kalastus", trans.giveTransaction(2)); 
    assertEquals("From: Transaktio line: 356", "1949", trans.giveTransaction(3)); 
    assertEquals("From: Transaktio line: 357", "22", trans.giveTransaction(4)); 
  } // Generated by ComTest END
}