package osakerekisteri.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import osakerekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.06 18:08:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TransaktioTest {



  // Generated by ComTest BEGIN
  /** testRegister107 */
  @Test
  public void testRegister107() {    // Transaktio: 107
    Transaktio trans1 = new Transaktio(); 
    assertEquals("From: Transaktio line: 109", 0, trans1.getTransactionId()); 
    trans1.register(); 
    Transaktio trans2 = new Transaktio(); 
    trans2.register(); 
    int n1 = trans1.getTransactionId(); 
    int n2 = trans2.getTransactionId(); 
    assertEquals("From: Transaktio line: 115", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString213 */
  @Test
  public void testToString213() {    // Transaktio: 213
    Transaktio transaktio = new Transaktio(); 
    transaktio.parse("1 | 1 | 2007-11-30 | Osto | 27.32 | 200 | 54.64 | 5518.64 |"); 
    assertEquals("From: Transaktio line: 216", "1|1|2007-11-30|Osto|27.32|200|54.64|5518.64|", transaktio.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse238 */
  @Test
  public void testParse238() {    // Transaktio: 238
    Transaktio transaction = new Transaktio(); 
    transaction.parse("1 | 1 | 2007-11-30 | Osto | 27.32 | 200 | 54.64 | 5518.64 |"); 
    assertEquals("From: Transaktio line: 241", 1, transaction.getTransactionId()); 
    assertEquals("From: Transaktio line: 242", true, transaction.toString().startsWith("1|1|2007-11-30|Osto|27.32|200|54.64|5518.64|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    transaction.register(); 
    int n = transaction.getTransactionId(); 
    transaction.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    transaction.register();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Transaktio line: 248", n+20+1, transaction.getTransactionId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone302 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone302() throws CloneNotSupportedException {    // Transaktio: 302
    Transaktio trans = new Transaktio(); 
    trans.parse("1|1|2007-11-30|Osto|27.32|200|54.64|5518.64|1"); 
    Transaktio klooni = trans.clone(); 
    assertEquals("From: Transaktio line: 307", trans.toString(), klooni.toString()); 
    trans.parse("2|2|2007-11-30|Myynti|25.00|100|10.00|2500.00|1"); 
    assertEquals("From: Transaktio line: 309", false, klooni.toString().equals(trans.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGiveTransaction361 */
  @Test
  public void testGiveTransaction361() {    // Transaktio: 361
    Transaktio trans = new Transaktio(); 
    trans.parse("1|1|2007-11-30|Osto|27.32|200|54.64|5518.64|"); 
    assertEquals("From: Transaktio line: 364", "Osto", trans.giveTransaction(0)); 
    assertEquals("From: Transaktio line: 365", "2007-11-30", trans.giveTransaction(1)); 
    assertEquals("From: Transaktio line: 366", "200", trans.giveTransaction(2)); 
    assertEquals("From: Transaktio line: 367", "27.32", trans.giveTransaction(3)); 
    assertEquals("From: Transaktio line: 368", "54.64", trans.giveTransaction(4)); 
    assertEquals("From: Transaktio line: 369", "5518.64", trans.giveTransaction(5)); 
  } // Generated by ComTest END
}